[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
description=""
version = "0.0.0"
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
pandas = "^1.0.5"
dash = "^1.13.3"
dash-core-components = "^1.10.1"
dash-html-components = "^1.0.3"
